apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pagesG3
  name: pages
  namespace: gamma3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagesG3
  strategy: {}
  template: 
    metadata:
      labels:
        app: pagesG3
    spec:
      containers:
      - image: aksjabindocker/pages:pipeline
        name: pages
        ports:
          - containerPort: 8080
        env:
          - name: PAGE_CONTENT
            valueFrom:
              configMapKeyRef:
                name: pages-config-map
                key: PAGE_CONTENT
